[
    {
      "detail": [
        {
          "description": "HIGH Vulnerability found in non-os package type (test) - /usr/local/bin/testbinary (CVE-2022-1234)",
          "gate": "vulnerabilities",
          "imageId": "d26f0119b9634091a541b081dd8bdca435ab52e114e4b4328575c0bc2c69768b",
          "policyId": "SoftwareChecks",
          "status": "stop",
          "tag": "test/testimage:testtag",
          "triggerId": "CVE-2022-1234+test",
          "triggerName": "package"
        },
        {
          "description": "MEDIUM Vulnerability found in non-os package type (test2) - /usr/local/bin/testbinary (fixed in: 1.2.3)(GHSA-1234-abcd-5678)",
          "gate": "vulnerabilities",
          "imageId": "d26f0119b9634091a541b081dd8bdca435ab52e114e4b4328575c0bc2c69768b",
          "policyId": "SoftwareChecks",
          "status": "stop",
          "tag": "test/testimage:testtag",
          "triggerId": "GHSA-1234-abcd-5678+test2",
          "triggerName": "package"
        },
        {
          "description": "User root found as effective user, which is not on the allowed list",
          "gate": "dockerfile",
          "imageId": "d26f0119b9634091a541b081dd8bdca435ab52e114e4b4328575c0bc2c69768b",
          "policyId": "RootUser",
          "status": "warn",
          "tag": "test/testimage:testtag",
          "triggerId": "b2605c2ddbdb02b8e2365c9248dada5a",
          "triggerName": "effective_user"
        }
      ],
      "digest": "sha256:8htz0bf942cfcd6hg8cf6435afd318b65d23e4c1a80044304c6e3ed20",
      "finalAction": "stop",
      "finalActionReason": "policy_evaluation",
      "lastEvaluation": "2022-09-20T08:25:52Z",
      "policyId": "9e104ade-7b57-4cdc-93fb-4949bf3b36b6",
      "status": "fail",
      "tag": "test/testimage:testtag"
    }
  ]
  